package ObjectLabEnterpriseSoftware;

import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

public class AddPrinter extends javax.swing.JFrame {

    /**
     * Creates new form AddPrinter
     */
    Device device;
    JTextField tfield;
    JLabel tlabel;
    //ArrayList of text fields and labels for adding and removing
    ArrayList<JTextField> fields = new ArrayList<JTextField>();
    ArrayList<JLabel> labels = new ArrayList<JLabel>();
    //Positioning variable for labels and fields
    private int y = 120;
    private final int COUNTMAX = 15;
    private final int COUNTMIN = 3;
    //Current count of labels and fields
    private int count = COUNTMIN;
    public void AddPrinterStart() {
        initComponents();
	fields.add(printerNameTF);
	fields.add(fileExtensionTF);
	fields.add(fieldTF0);
	labels.add(printerNameL);
	labels.add(fileExtensionL);
	labels.add(fieldL0);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel4 = new javax.swing.JLabel();
                jLabel1 = new javax.swing.JLabel();
                jSeparator1 = new javax.swing.JSeparator();
                printerNameTF = new javax.swing.JTextField();
                fileExtensionTF = new javax.swing.JTextField();
                printerNameL = new javax.swing.JLabel();
                removeFieldButton = new javax.swing.JButton();
                fieldL0 = new javax.swing.JLabel();
                addFieldButton = new javax.swing.JButton();
                saveBtn = new javax.swing.JButton();
                cancelBtn = new javax.swing.JButton();
                fieldTF0 = new javax.swing.JTextField();
                tfield1 = new javax.swing.JTextField();
                fileExtensionL = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jMenuBar1 = new javax.swing.JMenuBar();
                EditMenu = new javax.swing.JMenu();
                jMenuItem1 = new javax.swing.JMenuItem();

                jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ObjectLabEnterpriseSoftware/black and white bg.jpg"))); // NOI18N
                jLabel4.setPreferredSize(new java.awt.Dimension(600, 300));

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                setMinimumSize(new java.awt.Dimension(530, 475));
                getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jLabel1.setText("Add Printer");
                getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 21, -1, -1));
                getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, 470, 10));
                getContentPane().add(printerNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 124, -1));
                getContentPane().add(fileExtensionTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 124, -1));

                printerNameL.setText("Printer Name:");
                getContentPane().add(printerNameL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

                removeFieldButton.setText("Remove Field");
                removeFieldButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                removeFieldButtonActionPerformed(evt);
                        }
                });
                getContentPane().add(removeFieldButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 100, 20));

                fieldL0.setText("Field:");
                getContentPane().add(fieldL0, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

                addFieldButton.setText("Add Field");
                addFieldButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                addFieldButtonActionPerformed(evt);
                        }
                });
                getContentPane().add(addFieldButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 90, 20));

                saveBtn.setText("Save");
                saveBtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                saveBtnActionPerformed(evt);
                        }
                });
                getContentPane().add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 90, 20));

                cancelBtn.setText("Cancel");
                cancelBtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cancelBtnActionPerformed(evt);
                        }
                });
                getContentPane().add(cancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 100, 20));

                fieldTF0.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                fieldTF0ActionPerformed(evt);
                        }
                });
                getContentPane().add(fieldTF0, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 124, -1));
                getContentPane().add(tfield1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 124, -1));

                fileExtensionL.setText("File Ext.:");
                getContentPane().add(fileExtensionL, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ObjectLabEnterpriseSoftware/black and white bg.jpg"))); // NOI18N
                getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 720));

                EditMenu.setText("Help");

                jMenuItem1.setText("Contents");
                jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jMenuItem1ActionPerformed(evt);
                        }
                });
                EditMenu.add(jMenuItem1);

                jMenuBar1.add(EditMenu);

                setJMenuBar(jMenuBar1);

                pack();
                setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        //home.studentSubmissionButton.setVisible(false);
        dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed


    private void addFieldButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFieldButtonActionPerformed
        boolean add = true;
        /*if (printerNameTF.getText().equals("") || tfield0.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please fill out the previous fields before adding new ones.");
            add = false;
        }*/
            for (int i = 0; i < count; i++) {
                if (fields.get(i).getText().equals("")) {
                    add = false;
                    JOptionPane.showMessageDialog(this, "Please fill out the previous fields before adding new ones.");
                    break;
                }
            }
        
        if (count <= COUNTMAX && add == true) {
            tfield = new JTextField();
            tfield.setName("tfield" + (count-1));
            fields.add(tfield);
            tlabel = new JLabel();
            tlabel.setName("fieldL" + (count-1));
            tlabel.setText("Field #" + (count-1));
            labels.add(tlabel);
            y += 30;
            getContentPane().add(fields.get(count), new org.netbeans.lib.awtextra.AbsoluteConstraints(90, y, 124, -1), 4);
            getContentPane().add(labels.get(count), new org.netbeans.lib.awtextra.AbsoluteConstraints(30, y, -1, -1), 3);
            fields.get(count).setVisible(true);
            labels.get(count).setVisible(true);
            count++;
            revalidate();
            repaint();
        }
    }//GEN-LAST:event_addFieldButtonActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        boolean exit = true;
	device = new Device();
	//Check all text fields to make sure they aren't empty
        for (int i = 0; i < count; i++) {
            if (fields.get(i).getText().equals("")) {
                exit = false;
                JOptionPane.showMessageDialog(this, "Cannot save with empty fields!");
                break;
            }
        }
	if(exit==true){
		for (int i = 0; i < count; i++){
			for(int j = 0; j < count; j++){
				if(i!=j&&fields.get(i).getText().equals(
					fields.get(j).getText())){
					exit = false;
					JOptionPane.showMessageDialog(this, "Cannot save with duplicate fields");
					break;
				}
			}
			if(exit==false)
				break;
		}
	}
	//Add all values to the device class here
	ArrayList<String> values = new ArrayList<String>();
        if (exit==true) {
            for (int i = 0; i < count; i++) {
                values.add(fields.get(i).getText());
            }
	    device.setFieldNames(values);
            dispose();
        }
    }//GEN-LAST:event_saveBtnActionPerformed

        private void removeFieldButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeFieldButtonActionPerformed
            if (count != COUNTMIN) {
                y -= 30;
                count--;
                getContentPane().remove(fields.get(count));
                getContentPane().remove(labels.get(count));
                fields.remove(count);
                labels.remove(count);
                revalidate();
                repaint();
            }
        }//GEN-LAST:event_removeFieldButtonActionPerformed

        private void fieldTF0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldTF0ActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_fieldTF0ActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JMenu EditMenu;
        private javax.swing.JButton addFieldButton;
        private javax.swing.JButton cancelBtn;
        private javax.swing.JLabel fieldL0;
        private javax.swing.JTextField fieldTF0;
        private javax.swing.JLabel fileExtensionL;
        private javax.swing.JTextField fileExtensionTF;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JMenuBar jMenuBar1;
        private javax.swing.JMenuItem jMenuItem1;
        private javax.swing.JSeparator jSeparator1;
        private javax.swing.JLabel printerNameL;
        private javax.swing.JTextField printerNameTF;
        private javax.swing.JButton removeFieldButton;
        private javax.swing.JButton saveBtn;
        private javax.swing.JTextField tfield1;
        // End of variables declaration//GEN-END:variables
}
