package ObjectLabEnterpriseSoftware;

import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


/**
 *
 * @author Nick
 */
public class AddPrinter extends javax.swing.JFrame {

    /**
     * Creates new form AddPrinter
     */
    InstanceCall Inst;
    JTextField tfield;
    JLabel tlabel;
    //ArrayList of text fields and labels for adding and removing
    ArrayList<JTextField> fields = new ArrayList<JTextField>();
    ArrayList<JLabel> labels = new ArrayList<JLabel>();
    //Positioning variable for labels and fields
    private int y = 90;
    //Current count of labels and fields
    private int count = 0;
    private int countMax=15;
    public void AddPrinterStart() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel1 = new javax.swing.JLabel();
                jSeparator1 = new javax.swing.JSeparator();
                printerNameTF = new javax.swing.JTextField();
                tfield0 = new javax.swing.JTextField();
                printerNameL = new javax.swing.JLabel();
                removeFieldButton = new javax.swing.JButton();
                fieldL0 = new javax.swing.JLabel();
                addFieldButton = new javax.swing.JButton();
                saveBtn = new javax.swing.JButton();
                cancelBtn = new javax.swing.JButton();
                jLabel4 = new javax.swing.JLabel();
                jMenuBar1 = new javax.swing.JMenuBar();
                EditMenu = new javax.swing.JMenu();
                jMenuItem1 = new javax.swing.JMenuItem();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                setMinimumSize(new java.awt.Dimension(530, 475));
                setPreferredSize(new java.awt.Dimension(300, 700));
                getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jLabel1.setText("Add Printer");
                getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 21, -1, -1));
                getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, 470, 10));
                getContentPane().add(printerNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 124, -1));
                getContentPane().add(tfield0, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 124, -1));

                printerNameL.setText("Printer Name:");
                getContentPane().add(printerNameL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

                removeFieldButton.setText("Remove Field");
                removeFieldButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                removeFieldButtonActionPerformed(evt);
                        }
                });
                getContentPane().add(removeFieldButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, -1));

                fieldL0.setText("Field:");
                getContentPane().add(fieldL0, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

                addFieldButton.setText("Add Field");
                addFieldButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                addFieldButtonActionPerformed(evt);
                        }
                });
                getContentPane().add(addFieldButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));

                saveBtn.setText("Save");
                saveBtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                saveBtnActionPerformed(evt);
                        }
                });
                getContentPane().add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, -1, -1));

                cancelBtn.setText("Cancel");
                cancelBtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cancelBtnActionPerformed(evt);
                        }
                });
                getContentPane().add(cancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

                jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ObjectLabEnterpriseSoftware/black and white bg.jpg"))); // NOI18N
                jLabel4.setPreferredSize(new java.awt.Dimension(600, 300));
                getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -26, 730, 670));

                EditMenu.setText("Help");

                jMenuItem1.setText("Contents");
                jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jMenuItem1ActionPerformed(evt);
                        }
                });
                EditMenu.add(jMenuItem1);

                jMenuBar1.add(EditMenu);

                setJMenuBar(jMenuBar1);

                pack();
                setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        //home.studentSubmissionButton.setVisible(false);
        dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed
    
    
    private void addFieldButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFieldButtonActionPerformed
	    boolean add=true;
	    if(printerNameTF.getText().equals("")||tfield0.getText().equals("")){
		    JOptionPane.showMessageDialog(this,"Please fill out the previous fields before adding new ones.");
		    add=false;
	    }
	    if(count!=0&&add==true){
		   for(int i = 0; i < count; i++){
			if(fields.get(i).getText().equals("")){
				add=false;
				JOptionPane.showMessageDialog(this,"Please fill out the previous fields before adding new ones.");
				break;
			}
		} 
	    }
	    if(count<=countMax&&add==true){
		tfield = new JTextField();
		tfield.setName("tfield"+count);
		fields.add(tfield);
		tlabel = new JLabel();
		tlabel.setName("fieldL"+count);
		tlabel.setText("Field #"+count);
		labels.add(tlabel);
		y+=30;
		getContentPane().add(fields.get(count), new org.netbeans.lib.awtextra.AbsoluteConstraints(90, y, 124, -1),4);
		getContentPane().add(labels.get(count), new org.netbeans.lib.awtextra.AbsoluteConstraints(30, y, -1, -1),3);
		fields.get(count).setVisible(true);
		labels.get(count).setVisible(true);
		count++;
		revalidate();
		repaint();
	    }
	    if(count==0)
		    removeFieldButton.enable();
	    else
		    removeFieldButton.disable();
    }//GEN-LAST:event_addFieldButtonActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
	    boolean exit=true;
	    if(printerNameTF.getText().equals("")||tfield0.getText().equals("")){
		    JOptionPane.showMessageDialog(this,"Cannot save with empty fields!");
		    exit=false;
	    }
	    if(exit==true)
		for(int i = 0; i < count; i++){
			if(fields.get(i).getText().equals("")){
				exit=false;
				JOptionPane.showMessageDialog(this,"Cannot save with empty fields!");
				break;
			}
		}
	    if(exit==true)
		    dispose();
    }//GEN-LAST:event_saveBtnActionPerformed

        private void removeFieldButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeFieldButtonActionPerformed
		if(count!=0){
			y-=30;
			count--;
			getContentPane().remove(fields.get(count));
			getContentPane().remove(labels.get(count));
			fields.remove(count);
			labels.remove(count);
			revalidate();
			repaint();
		}
        }//GEN-LAST:event_removeFieldButtonActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JMenu EditMenu;
        private javax.swing.JButton addFieldButton;
        private javax.swing.JButton cancelBtn;
        private javax.swing.JLabel fieldL0;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JMenuBar jMenuBar1;
        private javax.swing.JMenuItem jMenuItem1;
        private javax.swing.JSeparator jSeparator1;
        private javax.swing.JLabel printerNameL;
        private javax.swing.JTextField printerNameTF;
        private javax.swing.JButton removeFieldButton;
        private javax.swing.JButton saveBtn;
        private javax.swing.JTextField tfield0;
        // End of variables declaration//GEN-END:variables
}
