package ObjectLabEnterpriseSoftware;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;

public class MainView extends javax.swing.JFrame
{
    private static final String NAME_OF_PAGE = "Home";

    AddStudentView newStudentSys;
	UpdateStudentView updateStudentSys;
    JobsView pendingSys;
    StudentSubmissionView studentSys;
    boolean show;
    String PASS = "ForwardMotion";

    public MainView()
    {
        initComponents();
        this.setResizable(false);
        setPrintersVisible(false);
        pendingSys = new JobsView();
        studentSys = new StudentSubmissionView();
        newStudentSys = new AddStudentView();
		updateStudentSys = new UpdateStudentView();
				
        //Allows only integers for student ID
        studentIdString.addKeyListener(new KeyAdapter()
        {
            public void keyTyped(KeyEvent e)
            {
                char c = e.getKeyChar();
                if (!((c >= '0') && (c <= '9')
                        || (c == KeyEvent.VK_BACK_SPACE)
                        || (c == KeyEvent.VK_DELETE)))
                {
                    getToolkit().beep();
                    e.consume();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        errorIdLabel = new javax.swing.JLabel();
        studentIdString = new javax.swing.JTextField();
        studentButton = new javax.swing.JButton();
        enterBuild = new javax.swing.JButton();
        openProjectsButton = new javax.swing.JButton();
        settingsButton = new javax.swing.JButton();
        AdminButton = new javax.swing.JButton();
        ReportsButton = new javax.swing.JButton();
        logoutB = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        MenuBar = new javax.swing.JMenuBar();
        helpButton = new javax.swing.JMenu();
        userGuideButton = new javax.swing.JMenuItem();
        userOptionsMenu = new javax.swing.JMenu();
        newStudentOption = new javax.swing.JMenuItem();
        updateStudentOption = new javax.swing.JMenuItem();

        jList1.setModel(new javax.swing.AbstractListModel()
        {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Art 101-001\nArt 201-002\nArt 401-004\nArt 501-005\nArt 601-006\nArt 701-007\nArt 801-009");
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(UtilController.getPageName(NAME_OF_PAGE));
        setMinimumSize(new java.awt.Dimension(250, 370));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        errorIdLabel.setBackground(new java.awt.Color(0, 0, 0));
        errorIdLabel.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(errorIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 130, 20));

        studentIdString.setToolTipText("Enter seven digit student ID.");
        studentIdString.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                studentIdStringActionPerformed(evt);
            }
        });
        getContentPane().add(studentIdString, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 130, 30));

        studentButton.setBackground(new java.awt.Color(0, 0, 0));
        studentButton.setText("Login");
        studentButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                studentButtonActionPerformed(evt);
            }
        });
        getContentPane().add(studentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 80, 30));

        enterBuild.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ObjectLabEnterpriseSoftware/images/hammer_icon.png"))); // NOI18N
        enterBuild.setToolTipText("Enter Build");
        enterBuild.setContentAreaFilled(false);
        enterBuild.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                enterBuildActionPerformed(evt);
            }
        });
        getContentPane().add(enterBuild, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 60, 60));

        openProjectsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ObjectLabEnterpriseSoftware/images/clipboard_icon.png"))); // NOI18N
        openProjectsButton.setToolTipText("Approve/Reject Projects");
        openProjectsButton.setContentAreaFilled(false);
        openProjectsButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                openProjectsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(openProjectsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 60, 60));

        settingsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ObjectLabEnterpriseSoftware/images/cog_icon.png"))); // NOI18N
        settingsButton.setToolTipText("Settings");
        settingsButton.setContentAreaFilled(false);
        settingsButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                settingsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(settingsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 60, 70));

        AdminButton.setBackground(new java.awt.Color(0, 0, 0));
        AdminButton.setText("Administrator");
        AdminButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                AdminButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AdminButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 100, 30));

        ReportsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ObjectLabEnterpriseSoftware/images/reports_icon.png"))); // NOI18N
        ReportsButton.setToolTipText("Reports");
        ReportsButton.setContentAreaFilled(false);
        ReportsButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ReportsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ReportsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 60, -1));

        logoutB.setBackground(new java.awt.Color(0, 0, 0));
        logoutB.setText("Logout");
        logoutB.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                logoutBActionPerformed(evt);
            }
        });
        getContentPane().add(logoutB, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 100, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ObjectLabEnterpriseSoftware/images/main_logo.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, -1));

        label1.setText("(c) 2015, Fouche Industries, LLC");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ObjectLabEnterpriseSoftware/images/white_bg.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 360));

        helpButton.setText("Help");

        userGuideButton.setText("User Guide");
        userGuideButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                userGuideButtonActionPerformed(evt);
            }
        });
        helpButton.add(userGuideButton);

        MenuBar.add(helpButton);

        userOptionsMenu.setText("User Options");
        userOptionsMenu.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                userOptionsMenuActionPerformed(evt);
            }
        });

        newStudentOption.setText("Add User");
        newStudentOption.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                newStudentOptionActionPerformed(evt);
            }
        });
        userOptionsMenu.add(newStudentOption);

        updateStudentOption.setText("Update User Login Info");
        updateStudentOption.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                updateStudentOptionActionPerformed(evt);
            }
        });
        userOptionsMenu.add(updateStudentOption);

        MenuBar.add(userOptionsMenu);

        setJMenuBar(MenuBar);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void enterBuildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterBuildActionPerformed
        // TODO add your handling code here:
        PrinterBuildView Build = new PrinterBuildView();
        Build.startMakeBuildProcess();
        dispose();
    }//GEN-LAST:event_enterBuildActionPerformed

    private void openProjectsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openProjectsButtonActionPerformed
        // TODO add your handling code here:
        pendingSys.PendingJobsStart();
        dispose();
    }//GEN-LAST:event_openProjectsButtonActionPerformed

    private void AdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminButtonActionPerformed
        PasswordDialogView dialogue = new PasswordDialogView();
        dialogue.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        dialogue.setAlwaysOnTop(true);
        dialogue.setVisible(true);
        dialogue.setLocationRelativeTo(this);
        dialogue.setResizable(false);
		
		//Handling code for proper submission
		setPrintersVisible(true);
		
        /* 
         Currently bypasses what is typed into dialogue for ease of testing
         password.equals(PASS) 
         */
		hideStudentOptions();

        //    JOptionPane.showMessageDialog(new java.awt.Frame(), "Incorrect password! Access Denied!");

    }//GEN-LAST:event_AdminButtonActionPerformed

    private void ReportsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportsButtonActionPerformed
        // TODO add your handling code here:
        ReportsView reports = new ReportsView();
		reports.setLocationRelativeTo(this);
        reports.ReportsPage();
        dispose();
    }//GEN-LAST:event_ReportsButtonActionPerformed

	public void resetAdminMode()
	{
			setPrintersVisible(true);
			hideStudentOptions();
		    setVisible(true);
	}
	public void hideStudentOptions()
	{
		studentButton.setVisible(false);
		studentIdString.setVisible(false);
		AdminButton.setVisible(false);
	}
	
	public void showStudentOptions()
	{
		studentButton.setVisible(true);
		studentIdString.setVisible(true);
		AdminButton.setVisible(true);
	}
	
    private void studentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentButtonActionPerformed
        // TODO add your handling code here:
        setPrintersVisible(false);

        String idString = studentIdString.getText();//DB team this is to store String

        if (idString.length() != 7)
        {
            errorIdLabel.setText("USER ID must be 7 digits");
        } else
        {
            if (UtilController.userIDExist(idString))
            {
                errorIdLabel.setText("");
                dispose();
                studentSys.studentSubmissionStart(idString);
            } else
            {
                errorIdLabel.setText("USER ID does not exist");
            }
        }
    }//GEN-LAST:event_studentButtonActionPerformed

    private void studentIdStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentIdStringActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_studentIdStringActionPerformed

    private void userGuideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userGuideButtonActionPerformed
        UtilController.openAdminHelpPage();
    }//GEN-LAST:event_userGuideButtonActionPerformed

    private void logoutBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBActionPerformed
        setPrintersVisible(false);
		showStudentOptions();
    }//GEN-LAST:event_logoutBActionPerformed

    private void userOptionsMenuActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_userOptionsMenuActionPerformed
    {//GEN-HEADEREND:event_userOptionsMenuActionPerformed
	// Nothing
    }//GEN-LAST:event_userOptionsMenuActionPerformed

    private void updateStudentOptionActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_updateStudentOptionActionPerformed
    {//GEN-HEADEREND:event_updateStudentOptionActionPerformed
        setPrintersVisible(false);

        String idString = studentIdString.getText(); //DB team this is to store String
        if (idString.length() != 7)
        {
            errorIdLabel.setText("USER ID must be 7 digits");
        } else
        {
            if (UtilController.userIDExist(idString))
            {
                errorIdLabel.setText("");
                dispose();
                updateStudentSys.UpdateStudentViewStart(idString);
            } else
            {
                errorIdLabel.setText("USER ID does not exist");
            }
        }
    }//GEN-LAST:event_updateStudentOptionActionPerformed

    private void newStudentOptionActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_newStudentOptionActionPerformed
    {//GEN-HEADEREND:event_newStudentOptionActionPerformed
        newStudentSys.NewStudentViewStart();
        dispose();
    }//GEN-LAST:event_newStudentOptionActionPerformed

    private void settingsButtonActionPerformed(java.awt.event.ActionEvent evt)
    {
        AdminSettingsView ad = new AdminSettingsView();
        ad.AdminSettingsViewStart();
        dispose();
    }

    public void setPrintersVisible(boolean isVisible)
    {
	studentButton.setVisible(!isVisible);
	studentIdString.setVisible(!isVisible);
	AdminButton.setVisible(!isVisible);
	AdminButton.setVisible(!isVisible);
	settingsButton.setVisible(isVisible);
	openProjectsButton.setVisible(isVisible);
	enterBuild.setVisible(isVisible);
	ReportsButton.setVisible(isVisible);
	logoutB.setVisible(isVisible);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Windows".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());

                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminButton;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JButton ReportsButton;
    private javax.swing.JButton enterBuild;
    private javax.swing.JLabel errorIdLabel;
    private javax.swing.JMenu helpButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private java.awt.Label label1;
    private javax.swing.JButton logoutB;
    private javax.swing.JMenuItem newStudentOption;
    private javax.swing.JButton openProjectsButton;
    private javax.swing.JButton settingsButton;
    private javax.swing.JButton studentButton;
    private javax.swing.JTextField studentIdString;
    private javax.swing.JMenuItem updateStudentOption;
    private javax.swing.JMenuItem userGuideButton;
    private javax.swing.JMenu userOptionsMenu;
    // End of variables declaration//GEN-END:variables
}
